ports:
  - port: 8000
tasks:
  - init: sudo apt install npm && curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash && sudo apt-get install nodejs && npm install --legacy-peer-deps
    command: npm run develop
